packages:
  - '.'
resolver: lts-14.1
extra-deps:
  - monad-metrics-0.2.1.4
  - wai-middleware-metrics-0.2.4
  - ekg-wai-0.1.0.3
  - ekg-json-0.1.0.6
  - wai-cli-0.2.0
  - refined-0.6.1
  - servant-server-0.18
  - servant-0.18
  - these-skinny-0.7.4

pvp-bounds: none
