name: Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.6.5", "8.8.4"]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: latest
        enable-stack: true

    - uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
